# Generated by Django 4.2.1 on 2023-05-16 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default=None, max_length=100)),
                ('Lname', models.CharField(default=None, max_length=100)),
                ('Nid', models.CharField(default=None, max_length=20)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Phone', models.CharField(default=None, max_length=20)),
                ('Address', models.CharField(default=None, max_length=255)),
                ('Birthday', models.DateField(default=datetime.date.today)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10)),
                ('Status', models.BooleanField()),
                ('Level', models.CharField(choices=[('First Level', 'First Level'), ('Second Level', 'Second Level'), ('Third Level', 'Third Level'), ('Fourth Level', 'Fourth Level')], default=None, max_length=100)),
                ('GPA', models.FloatField(default=0.0)),
                ('stuId', models.IntegerField(default=0)),
                ('department', models.CharField(choices=[('cs', 'CS'), ('ds', 'DS'), ('is', 'IS'), ('ai', 'AI')], default=None, max_length=100)),
            ],
        ),
    ]
