# Generated by Django 4.2.1 on 2023-05-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_firstname_student_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='none', upload_to='photo/%y/%m/%d'),
        ),
    ]
