# Generated by Django 4.2.1 on 2023-05-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='Fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Level',
            field=models.CharField(choices=[('First Level', 'First Level'), ('Second Level', 'Second Level'), ('Third Level', 'Third Level'), ('Fourth Level', 'Fourth Level')], default='First Level', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Nid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('cs', 'CS'), ('ds', 'DS'), ('is', 'IS'), ('ai', 'AI'), ('general', 'General')], default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuId',
            field=models.IntegerField(),
        ),
    ]
