# Generated by Django 4.2.1 on 2023-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_address_alter_student_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stuId',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(default='20230000', primary_key=True, serialize=False),
        ),
    ]
