# Generated by Django 4.2.1 on 2023-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('DS', 'DS'), ('IS', 'IS'), ('AI', 'AI'), ('General', 'General')], default='general', max_length=100),
        ),
    ]
